### ISSUE TITLE
Unused div element

### ISSUE THREAD

**Issue by jim-rosales** [TracyStoltz/prj-rev-bwfs-dasmoto#2]
It looks like this `<div>` is missing its closing tag `</div>`. Be careful when writing your HTML code since browsers are very lenient when it comes to syntax errors like in this case where everything renders as expected. Down the road though having syntax errors might cause troublesome bugs, so its best to avoid them. 

https://github.com/TracyStoltz/prj-rev-bwfs-dasmoto/blob/5564ef66b29a4b10e604a0b38ac93d341201f213/Dasmotos/index.html#L8

**Comment by TracyStoltz** [comment]
I made the changes:  space after alt and closing </div> tag it atom... I'm not sure how to correctly add - commit ? change in/on git ?

**Comment by jim-rosales** [comment]
No worries, it's not necessary to commit any changes. As long as you're aware of the issues and have fixed them on your local copy, that is sufficient!
